name: PR Review

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "dev"

jobs:
  review:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: "Install Dependencies"
        run: |
          yarn

      - name: "Lint Check"
        run: yarn workspaces run lint

      - name: "Build Check"
        run: yarn workspaces run build

      - name: "Unit test + Functional test"
        run: yarn workspaces run test