name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  define-apps:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    outputs:
      apps: ${{ steps.split_inputs.outputs.apps }}
    steps:
      - name: Extract tags from inputs
        id: split_inputs
        run: |
          APPS_JSON=$(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | tr -d '[],\"' | tr ' ' '\n' | jq -R -s -c 'split("\n")' | jq -c 'map(select(length > 0))')
          echo "::set-output name=matrix::"
          echo "apps=$APPS_JSON" >> $GITHUB_OUTPUT

  build:
    needs: define-apps
    runs-on: ubuntu-22.04
    environment: sy-ovh
    strategy:
      matrix:
        app: ${{fromJson(needs.define-apps.outputs.apps)}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 'Get tag version'
        run: |
          TAGNAME="${{ matrix.app }}"
          VER=${TAGNAME##*/}
          echo "Version $VER"
          echo "VERSION=$VER" >> $GITHUB_ENV
          APP_NAME=$(echo "$TAGNAME" | cut -d'/' -f2)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - name: 'Install dependencies'
        run: |
          yarn --frozen-lockfile
          yarn workspace @shineyup/${{ env.APP_NAME }} build
      
      - name: Build and push image
        run: |
          chmod +x ./deployments/${{ env.APP_NAME }}-docker-build.sh
          ./deployments/${{ env.APP_NAME }}-docker-build.sh "${{ env.VERSION }}"
          ./deployments/${{ env.APP_NAME }}-docker-build.sh "latest"

      - name: Release tag
        run: |
          git config --global user.email ""
          git config --global user.name "GitHub_Actions"
          git tag -a "${{ matrix.app }}" -m "${{ env.APP_NAME }} version ${{ env.VERSION }}"
          git push origin "${{ matrix.app }}"

  deploy:
    needs: [define-apps, build]
    runs-on: ubuntu-22.04
    environment: sy-ovh
    strategy:
      matrix:
        app: ${{fromJson(needs.define-apps.outputs.apps)}}
    steps:
      - uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User ubuntu
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.STAGING_PEM }}
          SSH_HOST: ${{ secrets.STAGING_HOST }}

      - name: 'Get app name'
        run: |
          TAGNAME="${{ matrix.app }}"
          APP_NAME=$(echo "$TAGNAME" | cut -d'/' -f2)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - name: Restart the app
        run: |
          chmod +x ./deployments/${{ env.APP_NAME }}-start.sh
          ./deployments/${{ env.APP_NAME }}-start.sh